<?php
// --- PHP BACKEND FOR GADGON ADMIN ---
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    header('Content-Type: application/json');
    
    // Save Config & Products to products.js
    if (isset($_GET['action']) && $_GET['action'] === 'save_data') {
        $input = file_get_contents('php://input');
        $data = json_decode($input, true);
        if ($data && isset($data['config']) && isset($data['products'])) {
            $config_js = "const GADGON_CONFIG = " . json_encode($data['config'], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . ";\n";
            $products_js = "const PRODUCTS = " . json_encode($data['products'], JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) . ";\n";
            $js_output = "/**\n * GADGON – Products Data\n * Auto-generated by Admin Dashboard\n */\n\n" . $config_js . "\n" . $products_js;
            file_put_contents('assets/js/products.js', $js_output);
            echo json_encode(["success" => true]);
        } else {
            echo json_encode(["success" => false, "message" => "Invalid data"]);
        }
        exit;
    }

    // Upload Hero Image
    if (isset($_GET['action']) && $_GET['action'] === 'save_hero') {
        if (isset($_FILES['hero_image']) && $_FILES['hero_image']['error'] === UPLOAD_ERR_OK) {
            $tmp_name = $_FILES['hero_image']['tmp_name'];
            $ext = strtolower(pathinfo($_FILES['hero_image']['name'], PATHINFO_EXTENSION));
            if (in_array($ext, ['jpg', 'jpeg', 'png', 'webp', 'gif'])) {
                // Overwrite the existing hero banner directly
                $destination = 'assets/images/hero-banner.png';
                move_uploaded_file($tmp_name, $destination);
                echo json_encode(["success" => true, "path" => $destination . '?v=' . time()]);
            } else {
                echo json_encode(["success" => false, "message" => "Invalid file type. Only jpg, png, webp, gif allowed."]);
            }
        } else {
            echo json_encode(["success" => false, "message" => "Upload error"]);
        }
        exit;
    }

    // Upload Product Image
    if (isset($_GET['action']) && $_GET['action'] === 'upload_product_image') {
        if (isset($_FILES['product_image']) && $_FILES['product_image']['error'] === UPLOAD_ERR_OK) {
            $tmp_name = $_FILES['product_image']['tmp_name'];
            $ext = strtolower(pathinfo($_FILES['product_image']['name'], PATHINFO_EXTENSION));
            if (in_array($ext, ['jpg', 'jpeg', 'png', 'webp', 'gif'])) {
                $filename = 'prod_' . time() . '.' . $ext;
                $destination = 'assets/images/' . $filename;
                move_uploaded_file($tmp_name, $destination);
                echo json_encode(["success" => true, "path" => $destination]);
            } else {
                echo json_encode(["success" => false, "message" => "Invalid file type"]);
            }
        } else {
            echo json_encode(["success" => false, "message" => "Upload error"]);
        }
        exit;
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GADGON Admin Dashboard</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-dark: #0a0a0f;
            --bg-card: #13131f;
            --primary: #9b59e8;
            --primary-hover: #b829ff;
            --text: #ffffff;
            --text-muted: rgba(255, 255, 255, 0.6);
            --border: rgba(255, 255, 255, 0.08);
            --danger: #ff4757;
        }

        * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-family: 'Outfit', sans-serif;
        }

        body {
            background-color: var(--bg-dark);
            color: var(--text);
            padding-bottom: 50px;
        }

        .header {
            background: rgba(19, 19, 31, 0.8);
            backdrop-filter: blur(10px);
            border-bottom: 1px solid var(--border);
            padding: 20px 40px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            position: sticky;
            top: 0;
            z-index: 100;
        }

        .header h1 {
            font-size: 24px;
            font-weight: 800;
            background: linear-gradient(135deg, #6c63ff, #b829ff);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        .btn {
            background: var(--primary);
            color: white;
            border: none;
            padding: 10px 20px;
            border-radius: 8px;
            font-weight: 600;
            cursor: pointer;
            transition: all 0.3s;
            display: inline-flex;
            align-items: center;
            gap: 8px;
            font-size: 14px;
        }

        .btn:hover {
            background: var(--primary-hover);
            transform: translateY(-2px);
        }

        .btn-outline {
            background: transparent;
            border: 1px solid var(--border);
            color: var(--text);
        }
        .btn-outline:hover {
            background: rgba(255,255,255,0.05);
            border-color: rgba(255,255,255,0.2);
        }

        .btn-danger {
            background: rgba(255, 71, 87, 0.1);
            color: var(--danger);
            border: 1px solid rgba(255, 71, 87, 0.2);
        }

        .btn-danger:hover {
            background: var(--danger);
            color: white;
        }

        .container {
            max-width: 1200px;
            margin: 40px auto;
            padding: 0 20px;
            display: grid;
            gap: 30px;
        }

        .section {
            background: var(--bg-card);
            border: 1px solid var(--border);
            border-radius: 16px;
            padding: 30px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.2);
        }

        .section-header {
            margin-bottom: 24px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .section-title {
            font-size: 18px;
            font-weight: 600;
        }

        .form-group {
            margin-bottom: 20px;
        }

        .form-label {
            display: block;
            margin-bottom: 8px;
            font-size: 14px;
            color: var(--text-muted);
        }

        .form-control {
            width: 100%;
            background: rgba(0,0,0,0.2);
            border: 1px solid var(--border);
            color: var(--text);
            padding: 12px 16px;
            border-radius: 8px;
            font-size: 15px;
            transition: border-color 0.3s;
        }

        .form-control:focus {
            outline: none;
            border-color: var(--primary);
        }

        .grid-2 {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
        }

        /* Products Grid Setup */
        .products-table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        .products-table th, .products-table td {
            padding: 16px;
            text-align: left;
            border-bottom: 1px solid var(--border);
        }

        .products-table th {
            color: var(--text-muted);
            font-size: 13px;
            text-transform: uppercase;
            letter-spacing: 1px;
            font-weight: 600;
        }

        .product-img-thumb {
            width: 50px;
            height: 50px;
            border-radius: 8px;
            object-fit: cover;
            background: rgba(255,255,255,0.05);
        }

        .product-actions {
            display: flex;
            gap: 10px;
        }

        /* Modal */
        .modal {
            position: fixed;
            inset: 0;
            background: rgba(0,0,0,0.8);
            backdrop-filter: blur(5px);
            z-index: 1000;
            display: flex;
            align-items: center;
            justify-content: center;
            opacity: 0;
            pointer-events: none;
            transition: opacity 0.3s;
        }

        .modal.active {
            opacity: 1;
            pointer-events: auto;
        }

        .modal-content {
            background: var(--bg-card);
            border: 1px solid var(--border);
            width: 90%;
            max-width: 600px;
            max-height: 90vh;
            border-radius: 20px;
            overflow-y: auto;
            transform: translateY(20px);
            transition: transform 0.3s;
        }

        .modal.active .modal-content {
            transform: translateY(0);
        }

        .modal-header {
            padding: 24px;
            border-bottom: 1px solid var(--border);
            display: flex;
            justify-content: space-between;
            align-items: center;
            position: sticky;
            top: 0;
            background: var(--bg-card);
            z-index: 10;
        }

        .modal-body {
            padding: 24px;
        }

        .close-btn {
            background: none;
            border: none;
            color: var(--text-muted);
            font-size: 24px;
            cursor: pointer;
        }

        .close-btn:hover {
            color: white;
        }

        /* Hero Image Setup */
        .hero-preview {
            width: 100%;
            max-width: 400px;
            height: 200px;
            border-radius: 12px;
            background: rgba(255,255,255,0.05);
            display: flex;
            align-items: center;
            justify-content: center;
            margin-bottom: 16px;
            overflow: hidden;
            border: 1px dashed var(--border);
        }

        .hero-preview img {
            width: 100%;
            height: 100%;
            object-fit: contain;
        }

        /* Loader */
        .loader-overlay {
            position: fixed;
            inset: 0;
            background: rgba(0,0,0,0.8);
            z-index: 2000;
            display: flex;
            align-items: center;
            justify-content: center;
            opacity: 0;
            pointer-events: none;
            transition: opacity 0.3s;
        }
        .loader-overlay.active {
            opacity: 1;
            pointer-events: auto;
        }

        .spinner {
            width: 40px;
            height: 40px;
            border: 4px solid rgba(255,255,255,0.1);
            border-left-color: var(--primary);
            border-radius: 50%;
            animation: spin 1s linear infinite;
        }

        @keyframes spin {
            to { transform: rotate(360deg); }
        }

        /* Toast */
        .toast {
            position: fixed;
            bottom: 30px;
            right: 30px;
            background: #2ed573;
            color: white;
            padding: 12px 24px;
            border-radius: 8px;
            font-weight: 500;
            transform: translateY(100px);
            opacity: 0;
            transition: all 0.3s;
            z-index: 3000;
            box-shadow: 0 5px 15px rgba(46, 213, 115, 0.3);
        }

        .toast.error {
            background: var(--danger);
            box-shadow: 0 5px 15px rgba(255, 71, 87, 0.3);
        }

        .toast.show {
            transform: translateY(0);
            opacity: 1;
        }
    </style>
</head>
<body>

    <div class="loader-overlay" id="loader">
        <div class="spinner"></div>
    </div>

    <div class="toast" id="toast">Changes saved successfully!</div>

    <header class="header">
        <h1>GADGON Admin</h1>
        <div>
            <a href="index.html" target="_blank" class="btn btn-outline" style="margin-right: 10px;">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"></path><polyline points="15 3 21 3 21 9"></polyline><line x1="10" y1="14" x2="21" y2="3"></line></svg>
                View Site
            </a>
            <button class="btn" onclick="saveAllData()">
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"></path><polyline points="17 21 17 13 7 13 7 21"></polyline><polyline points="7 3 7 8 15 8"></polyline></svg>
                Save Data
            </button>
        </div>
    </header>

    <div class="container">
        
        <!-- SETTINGS SECTION -->
        <div class="section">
            <div class="section-header">
                <h2 class="section-title">General Config (WhatsApp)</h2>
            </div>
            <div class="grid-2">
                <div class="form-group">
                    <label class="form-label">WhatsApp Number (e.g., 97477865120)</label>
                    <input type="text" class="form-control" id="cfg-wa" placeholder="Enter number with country code">
                </div>
                <div class="form-group">
                    <label class="form-label">Store Name</label>
                    <input type="text" class="form-control" id="cfg-name">
                </div>
            </div>
            <div class="form-group">
                <label class="form-label">WhatsApp Initial Greeting</label>
                <input type="text" class="form-control" id="cfg-greeting">
            </div>
        </div>

        <!-- HERO IMAGE SECTION -->
        <div class="section">
            <div class="section-header">
                <h2 class="section-title">Hero Banner Image</h2>
            </div>
            <div class="hero-preview" id="hero-preview-container">
                <img src="assets/images/hero-banner.png?v=<?php echo time(); ?>" id="hero-img-preview" alt="Hero Banner">
            </div>
            <div style="display: flex; gap: 10px; align-items: center;">
                <input type="file" id="hero-upload-input" accept="image/*" style="display: none;">
                <button class="btn btn-outline" onclick="document.getElementById('hero-upload-input').click()">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="17 8 12 3 7 8"></polyline><line x1="12" y1="3" x2="12" y2="15"></line></svg>
                    Select New Hero Image
                </button>
                <button class="btn" id="hero-save-btn" style="display: none;" onclick="uploadHeroImage()">
                    Upload Banner
                </button>
                <span id="hero-status" style="font-size: 14px; color: var(--text-muted);"></span>
            </div>
        </div>

        <!-- PRODUCTS SECTION -->
        <div class="section">
            <div class="section-header">
                <h2 class="section-title">Products Layout</h2>
                <button class="btn" onclick="openProductModal()">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>
                    Add Product
                </button>
            </div>
            <div style="overflow-x: auto;">
                <table class="products-table">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Name</th>
                            <th>Category</th>
                            <th>Price</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody id="products-tbody">
                        <!-- Rendered by JS -->
                    </tbody>
                </table>
            </div>
        </div>

    </div>

    <!-- PRODUCT MODAL -->
    <div class="modal" id="product-modal">
        <div class="modal-content">
            <div class="modal-header">
                <h3 id="modal-title">Edit Product</h3>
                <button class="close-btn" onclick="closeProductModal()">✕</button>
            </div>
            <div class="modal-body">
                <input type="hidden" id="prod-id">
                
                <div class="form-group">
                    <label class="form-label">Product Name</label>
                    <input type="text" class="form-control" id="prod-name">
                </div>

                <div class="grid-2">
                    <div class="form-group">
                        <label class="form-label">Category</label>
                        <select class="form-control" id="prod-category">
                            <option value="audio">Audio</option>
                            <option value="wearables">Wearables</option>
                            <option value="phones">Phones</option>
                            <option value="accessories">Accessories</option>
                            <option value="smart-home">Smart Home</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label class="form-label">Category Label (Emojis allowed)</label>
                        <input type="text" class="form-control" id="prod-categoryLabel" placeholder="e.g., 🎧 Audio">
                    </div>
                </div>

                <div class="grid-2">
                    <div class="form-group">
                        <label class="form-label">Price</label>
                        <input type="text" class="form-control" id="prod-price" placeholder="e.g., $89">
                    </div>
                    <div class="form-group">
                        <label class="form-label">Old Price (Optional)</label>
                        <input type="text" class="form-control" id="prod-oldPrice" placeholder="e.g., $129">
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-label">Badge</label>
                    <select class="form-control" id="prod-badge">
                        <option value="">None</option>
                        <option value="hot">Hot</option>
                        <option value="new">New</option>
                        <option value="sale">Sale</option>
                    </select>
                </div>

                <div class="form-group">
                    <label class="form-label">Product Image Path</label>
                    <div style="display: flex; gap: 10px;">
                        <input type="text" class="form-control" id="prod-image" placeholder="assets/images/product.png">
                        <input type="file" id="prod-upload-input" accept="image/*" style="display: none;">
                        <button class="btn btn-outline" style="min-width: 120px;" onclick="document.getElementById('prod-upload-input').click()">Upload</button>
                    </div>
                </div>

                <div class="form-group">
                    <label class="form-label">Description</label>
                    <textarea class="form-control" id="prod-desc" rows="3"></textarea>
                </div>

                <div class="form-group">
                    <label class="form-label">Specs (Comma separated)</label>
                    <input type="text" class="form-control" id="prod-specs" placeholder="ANC, 30hr Battery, Hi-Fi Sound">
                </div>

                <div style="display: flex; justify-content: flex-end; gap: 10px; margin-top: 30px;">
                    <button class="btn btn-outline" onclick="closeProductModal()">Cancel</button>
                    <button class="btn" onclick="saveProduct()">Save Product</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Script to load existing data -->
    <script src="assets/js/products.js?v=<?php echo time(); ?>"></script>
    
    <script>
        let configData = {};
        let productsData = [];

        // DOM Elements
        const tbody = document.getElementById('products-tbody');
        const modal = document.getElementById('product-modal');
        const loader = document.getElementById('loader');
        const toast = document.getElementById('toast');

        window.onload = () => {
            // Load from global variables provided by products.js
            try {
                configData = JSON.parse(JSON.stringify(GADGON_CONFIG));
                productsData = JSON.parse(JSON.stringify(PRODUCTS));
            } catch (e) {
                console.error("Error loading initial data", e);
                showToast("Error loading initial data", true);
            }

            // Populate Config Fields
            document.getElementById('cfg-wa').value = configData.whatsappNumber || '';
            document.getElementById('cfg-name').value = configData.storeName || '';
            document.getElementById('cfg-greeting').value = configData.greeting || '';

            renderProductsTable();
        };

        function showToast(message, isError = false) {
            toast.textContent = message;
            toast.className = 'toast show';
            if (isError) toast.classList.add('error');
            setTimeout(() => {
                toast.classList.remove('show');
            }, 3000);
        }

        // --- Render Products ---
        function renderProductsTable() {
            tbody.innerHTML = '';
            productsData.forEach((p, index) => {
                const tr = document.createElement('tr');
                tr.innerHTML = `
                    <td><img src="${p.image}" class="product-img-thumb" onerror="this.src='assets/images/hero-banner.png'"></td>
                    <td style="font-weight: 500;">${p.name}</td>
                    <td><span style="background: rgba(255,255,255,0.1); padding: 4px 10px; border-radius: 20px; font-size: 12px;">${p.categoryLabel || p.category}</span></td>
                    <td style="color: var(--primary); font-weight: 600;">${p.price}</td>
                    <td>
                        <div class="product-actions">
                            <button class="btn btn-outline" style="padding: 6px 12px; font-size: 13px;" onclick="openProductModal(${index})">Edit</button>
                            <button class="btn btn-danger" style="padding: 6px 12px; font-size: 13px;" onclick="deleteProduct(${index})">Delete</button>
                        </div>
                    </td>
                `;
                tbody.appendChild(tr);
            });
        }

        // --- Modal Logic ---
        function openProductModal(index = null) {
            if (index !== null) {
                // Edit Mode
                const p = productsData[index];
                document.getElementById('modal-title').innerText = 'Edit Product';
                document.getElementById('prod-id').value = p.id;
                document.getElementById('prod-name').value = p.name;
                document.getElementById('prod-category').value = p.category || 'audio';
                document.getElementById('prod-categoryLabel').value = p.categoryLabel || '';
                document.getElementById('prod-price').value = p.price;
                document.getElementById('prod-oldPrice').value = p.oldPrice || '';
                document.getElementById('prod-badge').value = p.badge || '';
                document.getElementById('prod-image').value = p.image || '';
                document.getElementById('prod-desc').value = p.description || '';
                document.getElementById('prod-specs').value = (p.specs || []).join(', ');
            } else {
                // Add Mode
                document.getElementById('modal-title').innerText = 'Add New Product';
                document.getElementById('prod-id').value = 'new';
                document.getElementById('prod-name').value = '';
                document.getElementById('prod-category').value = 'audio';
                document.getElementById('prod-categoryLabel').value = '🎧 Audio';
                document.getElementById('prod-price').value = '';
                document.getElementById('prod-oldPrice').value = '';
                document.getElementById('prod-badge').value = '';
                document.getElementById('prod-image').value = '';
                document.getElementById('prod-desc').value = '';
                document.getElementById('prod-specs').value = '';
            }
            modal.classList.add('active');
        }

        function closeProductModal() {
            modal.classList.remove('active');
        }

        // Auto-update category label safely
        document.getElementById('prod-category').addEventListener('change', function() {
            const map = {
                'audio': '🎧 Audio', 'wearables': '⌚ Wearables', 'phones': '📱 Phones',
                'accessories': '⚡ Accessories', 'smart-home': '🏠 Smart Home'
            };
            if(map[this.value]) {
                document.getElementById('prod-categoryLabel').value = map[this.value];
            }
        });

        function saveProduct() {
            const idVal = document.getElementById('prod-id').value;
            const newProduct = {
                id: idVal === 'new' ? Date.now() : parseInt(idVal),
                name: document.getElementById('prod-name').value,
                category: document.getElementById('prod-category').value,
                categoryLabel: document.getElementById('prod-categoryLabel').value,
                price: document.getElementById('prod-price').value,
                oldPrice: document.getElementById('prod-oldPrice').value,
                badge: document.getElementById('prod-badge').value,
                image: document.getElementById('prod-image').value,
                description: document.getElementById('prod-desc').value,
                specs: document.getElementById('prod-specs').value.split(',').map(s => s.trim()).filter(s => s !== '')
            };

            if (idVal === 'new') {
                productsData.unshift(newProduct);
            } else {
                const idx = productsData.findIndex(p => p.id == idVal);
                if(idx > -1) productsData[idx] = newProduct;
            }

            renderProductsTable();
            closeProductModal();
            showToast("Product updated temporarily. Don't forget to 'Save Data'!", false);
        }

        function deleteProduct(index) {
            if(confirm('Are you sure you want to delete this product?')) {
                productsData.splice(index, 1);
                renderProductsTable();
            }
        }

        // --- Master Save JSON ---
        function saveAllData() {
            // Update Config from forms
            configData.whatsappNumber = document.getElementById('cfg-wa').value;
            configData.storeName = document.getElementById('cfg-name').value;
            configData.greeting = document.getElementById('cfg-greeting').value;

            const payload = {
                config: configData,
                products: productsData
            };

            loader.classList.add('active');

            fetch('admin.php?action=save_data', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            })
            .then(res => res.json())
            .then(data => {
                loader.classList.remove('active');
                if (data.success) {
                    showToast("All data successfully saved to products.js!");
                } else {
                    showToast("Error saving data.", true);
                }
            })
            .catch(err => {
                loader.classList.remove('active');
                showToast("Network error saving data.", true);
            });
        }

        // --- Hero Image Upload ---
        let heroFile = null;
        document.getElementById('hero-upload-input').addEventListener('change', function(e) {
            if (e.target.files && e.target.files[0]) {
                heroFile = e.target.files[0];
                const url = URL.createObjectURL(heroFile);
                document.getElementById('hero-img-preview').src = url;
                document.getElementById('hero-save-btn').style.display = 'inline-flex';
                document.getElementById('hero-status').innerText = 'Ready to upload...';
            }
        });

        function uploadHeroImage() {
            if (!heroFile) return;
            const formData = new FormData();
            formData.append('hero_image', heroFile);

            document.getElementById('hero-status').innerText = 'Uploading...';
            document.getElementById('hero-save-btn').disabled = true;

            fetch('admin.php?action=save_hero', {
                method: 'POST',
                body: formData
            })
            .then(res => res.json())
            .then(data => {
                document.getElementById('hero-save-btn').disabled = false;
                if(data.success) {
                    document.getElementById('hero-save-btn').style.display = 'none';
                    document.getElementById('hero-status').innerText = 'Banner updated successfully!';
                    document.getElementById('hero-img-preview').src = data.path;
                    showToast("Hero banner updated!");
                } else {
                    document.getElementById('hero-status').innerText = 'Error: ' + data.message;
                    showToast("Error: " + data.message, true);
                }
            })
            .catch(err => {
                document.getElementById('hero-save-btn').disabled = false;
                document.getElementById('hero-status').innerText = 'Network error.';
            });
        }

        // --- Product Image Asset Upload ---
        document.getElementById('prod-upload-input').addEventListener('change', function(e) {
            if (e.target.files && e.target.files[0]) {
                const formData = new FormData();
                formData.append('product_image', e.target.files[0]);

                document.getElementById('prod-image').value = 'Uploading...';
                
                fetch('admin.php?action=upload_product_image', {
                    method: 'POST',
                    body: formData
                })
                .then(res => res.json())
                .then(data => {
                    if(data.success) {
                        document.getElementById('prod-image').value = data.path;
                        showToast("Image uploaded successfully!");
                    } else {
                        document.getElementById('prod-image').value = '';
                        alert('Upload failed: ' + data.message);
                    }
                })
                .catch(err => {
                    document.getElementById('prod-image').value = '';
                    alert('Network error during upload.');
                });
            }
        });
    </script>
</body>
</html>
